# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HASP Pytest

on: 
  push:
  pull_request:
  schedule:
    - cron: '00 00 * * *'  # every day at midnight

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    env: 
      lref: /grp/hst/cdbs/lref/
      oref: /grp/hst/cdbs/oref/ 
      working-directory: ./
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.11
            runs-on: ubuntu-latest
            python-version: '3.11'
            toxenv: py311

          - name: Python 3.10
            runs-on: ubuntu-latest
            python-version: '3.10'
            toxenv: py310
            
          - name: Python 3.9
            runs-on: ubuntu-latest
            python-version: '3.9'
            toxenv: py39
            
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install cython
        pip install astropy
        pip install scipy
        pip install matplotlib
        pip install stsci.tools==4.0.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Lint with flake8
#      run: |
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # run all the unit tests.
        pip install .['test']
        pip install 'ullyses @ git+https://github.com/spacetelescope/ullyses.git'
        pytest tests/test_swrapper.py -v 
      working-directory: ${{env.working-directory}}
